services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=blogdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=shashwat'
    ports:
      - '5432:5432'