spring:
  jpa:
    generate-ddl: true
  threads:
    virtual:
      enabled: true
  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        options:
          model: mistral
logging:
  level:
    org.atmosphere: warn